PatientsRegistry/Controllers/DoctorController.cs
using DataAccess.Entities;
using DataAccess.Repositories;
using PatientsRegistry.Filters;
using PatientsRegistry.Models;
using PatientsRegistry.ViewModels;
using PatientsRegistry.ViewModels.Doctor;
using System.Web.Mvc;

namespace PatientsRegistry.Controllers
{
    [Doctor]
    [Authenticate]
    public class DoctorController : BaseController<Appointment, AppointmentsListVM, AppointmentDetailsDoctor>
    {
        public override BaseRepository<Appointment> GetRepo()
        {
            return new AppointmentRepository();
        }

        // Index
        public override AppointmentsListVM PopulateListVM(AppointmentsListVM model)
        {
            TryUpdateModel(model);

            BaseRepository<Appointment> appRepo = GetRepo();
            model.Appointments = appRepo.GetAll(a => a.DoctorID == AuthenticationManager.LoggedUser.ID);

            return model;
        }

        // Details
        public override AppointmentDetailsDoctor PopulateDetailsVM(AppointmentDetailsDoctor model)
        {
            BaseRepository<Appointment> appRepo = GetRepo();
            Appointment app = appRepo.GetByID(model.ID);

            model.Date = app.Date;
            model.Status = app.Status;
            model.Patient = app.Patient.FullName;

            return model;
        }

        // Review GET
        [HttpGet]
        public ActionResult Review(int? id)
        {
            AppointmentRepository appRepo = new AppointmentRepository();
            Appointment app = appRepo.GetByID(id.Value);

            AppointmentReview model = new AppointmentReview()
            {
                ID = app.ID,
                PatientID = app.PatientID,
                DoctorID = app.DoctorID,
                Patient = app.Patient,
                Date = app.Date,
                Status = app.Status
            };

            return View(model);
        }

        // Review POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Review(AppointmentReview model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            AppointmentRepository appRepo = new AppointmentRepository();
            Appointment app = appRepo.GetByID(model.ID);

            if (Request.Form["Approve"] != null)
            {
                model = Approve(model);
            }
            else if (Request.Form["Decline"] != null)
            {
                model = Decline(model);
            }

            app.Status = model.Status;

            appRepo.Save(app);

            return RedirectToAction("Index");
        }

        // Approve
        private AppointmentReview Approve(AppointmentReview model)
        {
            model.Status = StatusEnum.Approved;
            return model;
        }

        // Decline
        private AppointmentReview Decline(AppointmentReview model)
        {
            model.Status = StatusEnum.Unapproved;
            return model;
        }
    }
}

PatientsRegistry/Controllers/PatientController.cs
using DataAccess.Entities;
using DataAccess.Repositories;
using PatientsRegistry.Filters;
using PatientsRegistry.Models;
using PatientsRegistry.ViewModels;
using PatientsRegistry.ViewModels.Patient;
using System;
using System.Data.Entity;
using System.Web.Mvc;

namespace PatientsRegistry.Controllers
{
    [Patient]
    [Authenticate]
    public class PatientController : BaseController<Appointment, AppointmentsListVM, AppointmentDetailsPatient>
    {
        // Repo
        public override BaseRepository<Appointment> GetRepo()
        {
            return new AppointmentRepository();
        }

        // Index
        public override AppointmentsListVM PopulateListVM(AppointmentsListVM model)
        {
            TryUpdateModel(model);

            BaseRepository<Appointment> appRepo = GetRepo();
            model.Appointments = appRepo.GetAll(a => a.PatientID == AuthenticationManager.LoggedUser.ID);

            return model;
        }

        // Details
        public override AppointmentDetailsPatient PopulateDetailsVM(AppointmentDetailsPatient model)
        {
            BaseRepository<Appointment> appRepo = GetRepo();
            Appointment app = appRepo.GetByID(model.ID);

            model.Date = app.Date;
            model.Status = app.Status;
            model.Doctor = app.Doctor.FullName;

            return model;
        }

        // Request GET
        [HttpGet]
        public new ActionResult Request()
        {
            AppointmentRequest model = new AppointmentRequest()
            {
                Date = DateTime.Now
            };
            return View(model);
        }

        // Request POST
        [HttpPost]
        public new ActionResult Request(AppointmentRequest model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Appointment app = new Appointment()
            {
                ID = model.ID,
                Date = model.Date,
                DoctorID = model.DoctorID,
                PatientID = AuthenticationManager.LoggedUser.ID
            };

            AppointmentRepository appRepo = new AppointmentRepository();

            // check if appointment already exists
            Appointment findApp = appRepo.GetFirst(a => (app.Date >= a.Date && app.Date <= DbFunctions.AddMinutes(a.Date, 30)) && app.DoctorID == a.DoctorID);
            if (findApp == null)
            {
                appRepo.Save(app);
            }

            else
            {
                ModelState.AddModelError(string.Empty, "There is already an appointment scheduled for this date and hour!");
                return View(model);
            }

            return RedirectToAction("Index");
        }

        // Reschedule GET
        [HttpGet]
        public ActionResult Reschedule(int? id)
        {
            AppointmentRepository appRepo = new AppointmentRepository();
            Appointment app = appRepo.GetByID(id.Value);

            AppointmentReschedule model = new AppointmentReschedule()
            {
                Date = app.Date
            };

            return View(model);
        }

        // Reschedule POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reschedule(AppointmentReschedule model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            AppointmentRepository appRepo = new AppointmentRepository();
            Appointment app = appRepo.GetByID(model.ID);

            app.Date = model.Date;
            app.Status = StatusEnum.Unknown;
            appRepo.Save(app);

            return RedirectToAction("Index");
        }
    }
}

PatientsRegistry/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Patients Registry</title>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    @RenderSection("head", required: false)
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            @Html.ActionLink("Patients Registry", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (PatientsRegistry.Models.AuthenticationManager.LoggedUser == null)
                    {
                        <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    }
                    else
                    {
                        if (PatientsRegistry.Models.AuthenticationManager.LoggedUser.IsDoctor == true)
                        {
                            <li>@Html.ActionLink("Appointments", "Index", "Doctor")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Appointments", "Index", "Patient")</li>
                        }

                        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Patients Registry</p>
        </footer>
    </div>

    <script src="~/scripts/jquery-2.0.3.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>